/*
 * Swagger Banking
 * Simple Banking API used for MOIS on UHK. Api is derived from AIR bank API: https://www.airbank.cz/novinky-z-airbank/2017/open-api/open-api-banking.html#top
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michal.gregor@uhk.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cz.kozenky.moispayments.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * foreign payments additional info (original value and exchange rate)
 */
@ApiModel(description = "foreign payments additional info (original value and exchange rate)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-22T10:39:10.089+02:00")
public class TransactionAdditionalInfoForeign {
  @JsonProperty("originalValue")
  private TransactionAdditionalInfoForeignOriginalValue originalValue = null;

  @JsonProperty("exchangeRate")
  private BigDecimal exchangeRate = null;

  public TransactionAdditionalInfoForeign originalValue(TransactionAdditionalInfoForeignOriginalValue originalValue) {
    this.originalValue = originalValue;
    return this;
  }

   /**
   * Get originalValue
   * @return originalValue
  **/
  @ApiModelProperty(value = "")
  public TransactionAdditionalInfoForeignOriginalValue getOriginalValue() {
    return originalValue;
  }

  public void setOriginalValue(TransactionAdditionalInfoForeignOriginalValue originalValue) {
    this.originalValue = originalValue;
  }

  public TransactionAdditionalInfoForeign exchangeRate(BigDecimal exchangeRate) {
    this.exchangeRate = exchangeRate;
    return this;
  }

   /**
   * exchange rate valid at the time of transfer
   * @return exchangeRate
  **/
  @ApiModelProperty(value = "exchange rate valid at the time of transfer")
  public BigDecimal getExchangeRate() {
    return exchangeRate;
  }

  public void setExchangeRate(BigDecimal exchangeRate) {
    this.exchangeRate = exchangeRate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionAdditionalInfoForeign transactionAdditionalInfoForeign = (TransactionAdditionalInfoForeign) o;
    return Objects.equals(this.originalValue, transactionAdditionalInfoForeign.originalValue) &&
        Objects.equals(this.exchangeRate, transactionAdditionalInfoForeign.exchangeRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalValue, exchangeRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionAdditionalInfoForeign {\n");
    
    sb.append("    originalValue: ").append(toIndentedString(originalValue)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

